language: cpp
dist: xenial
sudo: false

git:
  depth: false
  quiet: true

addons:
  apt:
    packages:
      - cmake
      - libegl1-mesa-dev
      - libglib2.0-dev
      - libxkbcommon-dev
      - libwayland-dev
      - ninja-build
      - libjson-glib-dev

env:
  matrix:
    - BUILD_TYPE=Debug   EXPORTABLE_EGL=ON
    - BUILD_TYPE=Release EXPORTABLE_EGL=OFF

cache:
  ccache: true
  directories:
    - $HOME/libwpe
    - $HOME/libwpe-build

install: |-
  : 'Checkout and install libwpe'
  set -e
  if [[ -d ~/libwpe/.git/ ]] ; then
    echo 'Cleaning libwpe clone...'
    pushd ~/libwpe/
    git reset --hard
    git clean -qxdff
    git checkout -f master
  else
    echo 'Cloning libwpe afresh...'
    rm -rf ~/libwpe/
    git clone -q https://github.com/WebPlatformForEmbedded/libwpe ~/libwpe/
    pushd ~/libwpe/
  fi
  mkdir -p ~/libwpe-build/ && cd "$_"
  cmake ~/libwpe/ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=${HOME}/libwpe-prefix -DCMAKE_INSTALL_LIBDIR=${HOME}/libwpe-prefix/lib
  TERM=dumb cmake --build . --parallel $(nproc) --target install
  popd

script: |-
  : 'Build'
  set -e
  mkdir _build/ && cd "$_"
  PKG_CONFIG_PATH=${HOME}/libwpe-prefix/lib/pkgconfig \
    cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  TERM=dumb cmake --build . --parallel $(nproc)
