---

name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Debian Packages
        run: |
          sudo apt update
          sudo apt install -y \
            cmake \
            flex \
            libclang-dev \
            libegl1-mesa-dev \
            libepoxy-dev \
            libglib2.0-dev \
            libjson-glib-dev \
            libwayland-dev \
            libxkbcommon-dev \
            libxml2-dev \
            libxslt1-dev \
            libyaml-dev \
            llvm-dev \
            ninja-build \
            python3-dev
      - name: Python Package Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.cache/pip/
            .venv/
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/ci.yml') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install Python Packages
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          HOTDOC_BUILD_C_EXTENSION: enabled
        run: |
          python3 -m venv --upgrade-deps .venv
          . .venv/bin/activate
          pip install meson==0.55 hotdoc scan-build
      - name: Fetch libwpe
        run: |
          if [[ -d ~/libwpe/.git ]] ; then
            echo 'Updating libwpe clone...'
            cd ~/libwpe/
            git reset --hard
            git clean -qxdff
            git checkout -f master
            git pull -q
          else
            echo 'Cloning libwpe afresh...'
            rm -rf ~/libwpe/
            git clone -q https://github.com/WebPlatformForEmbedded/libwpe ~/libwpe/
          fi
          mkdir -p subprojects
          ln -s ~/libwpe subprojects/
      - name: Configure
        run: |
          . .venv/bin/activate
          mkdir -p _work && meson _work/build --prefix /usr -Dbuild_docs=true
      - name: Build
        run: TERM=dumb ninja -C _work/build
      - name: Install
        run: |
          . .venv/bin/activate
          DESTDIR="$(pwd)/_work/files" ninja -C _work/build install
      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: _work
  analyze:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Tools
        run: |
          curl -sL https://apt.llvm.org/llvm-snapshot.gpg.key | \
            sudo apt-key add -
          sudo add-apt-repository \
            'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main'
          sudo apt update
          sudo apt install -y libxkbcommon-dev libegl1-mesa-dev libyaml-dev \
            libwayland-dev clang libglib2.0-dev libepoxy-dev ninja-build
      - name: Python Package Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.cache/pip/
            .venv/
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/ci.yml') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install Python Packages
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          HOTDOC_BUILD_C_EXTENSION: enabled
        run: |
          python3 -m venv --upgrade-deps .venv
          . .venv/bin/activate
          pip install meson==0.55 hotdoc scan-build
      - name: Fetch libwpe
        run: |
          if [[ -d ~/libwpe/.git ]] ; then
            echo 'Updating libwpe clone...'
            cd ~/libwpe/
            git reset --hard
            git clean -qxdff
            git checkout -f master
            git pull -q
          else
            echo 'Cloning libwpe afresh...'
            rm -rf ~/libwpe/
            git clone -q https://github.com/WebPlatformForEmbedded/libwpe ~/libwpe/
          fi
          mkdir -p subprojects
          ln -s ~/libwpe subprojects/
      - name: Configure
        run: |
          . .venv/bin/activate
          meson _work --prefix /usr -Dbuild_docs=false
      - name: Analyze
        run: |
          . .venv/bin/activate
          TERM=dumb ninja -C _work
          analyze-build \
            --enable-checker nullability.NullablePassedToNonnull \
            --enable-checker optin.cplusplus.UninitializedObject \
            --enable-checker optin.cplusplus.VirtualCall \
            --enable-checker optin.performance.Padding \
            --enable-checker optin.portability.UnixAPI \
            --enable-checker valist.CopyToSelf \
            --enable-checker valist.Uninitialized \
            --enable-checker valist.Unterminated \
            --cdb _work/compile_commands.json \
            -o _work/report
